version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - authentication_network
      - store_network

  authenticationDB:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - authentication_network

  authentication:
    build:
      context: .
      dockerfile: authentication.dockerfile
    image: authentication
    restart: always
    environment:
      - DATABASE_URL=authenticationDB
    ports:
      - 5002:5002
    networks:
      - authentication_network

  redis:
    image: redis
    restart: always
    ports:
    - 6379:6379
    networks:
      - store_network
    
  warehouse:
    build:
      context: .
      dockerfile: warehouse.dockerfile
    image: warehouse
    restart: always
    ports:
      - 5003:5003
    networks:
      - store_network

volumes:
  db-data:


networks:
  authentication_network:
  store_network:
