version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - authentication_network
      - store_network

  authenticationDB:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - authentication-db-data:/var/lib/mysql
    networks:
      - authentication_network

  authentication:
    build:
      context: .
      dockerfile: authentication.dockerfile
    image: 127.0.0.1:5000/authentication
    restart: always
    environment:
      - DATABASE_URL=authenticationDB
    ports:
      - 5002:5002
    networks:
      - authentication_network

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - products_ingester_network

  warehouse:
    build:
      context: .
      dockerfile: warehouse.dockerfile
    image: 127.0.0.1:5000/warehouse
    restart: always
    environment:
      - DATABASE_URL=storeDB
    ports:
      - 5003:5003
    networks:
      - products_ingester_network

  daemon:
    build:
      context: .
      dockerfile: daemon.dockerfile
    image: 127.0.0.1:5000/daemon
    restart: always
    environment:
      - DATABASE_URL=storeDB
    ports:
      - 5004:5004
    networks:
      - products_ingester_network
      - store_network

  storeDB:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - store-db-data:/var/lib/mysql
    networks:
      - store_network

  customer:
    build:
      context: .
      dockerfile: customer.dockerfile
    image: 127.0.0.1:5000/customer
    restart: always
    environment:
      - DATABASE_URL=storeDB
    ports:
      - 5005:5005
    networks:
      - store_network
  
  admin:
    build:
      context: .
      dockerfile: admin.dockerfile
    image: 127.0.0.1:5000/admin
    restart: always
    environment:
      - DATABASE_URL=storeDB
    ports:
      - 5006:5006
    networks:
      - store_network

volumes:
  authentication-db-data:
  store-db-data:


networks:
  authentication_network:
  store_network:
  products_ingester_network:
